### ISSUE TITLE
Connection destruction segfault

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq#13]
Forced disconnection in hta. Assuming this is a metricq / AMQP issue.

```
#0  0x00007fa85c44b91c in _int_free (av=0x7fa85c76db00 <main_arena>, p=0x1be97a0, have_lock=0) at malloc.c:4052
#1  0x00000000004925cd in __gnu_cxx::new_allocator<AMQP::CopiedBuffer>::deallocate (this=<optimized out>, __p=<optimized out>)
    at /home/service/metricq-db-hta/lib/metricq/lib/amqpcpp/include/amqpcpp/channelimpl.h:208
#2  std::allocator_traits<std::allocator<AMQP::CopiedBuffer> >::deallocate (__a=..., __n=16, __p=<optimized out>) at /opt/gcc/8.1.0/include/c++/8.1.0/bits/alloc_traits.h:462
#3  std::_Deque_base<AMQP::CopiedBuffer, std::allocator<AMQP::CopiedBuffer> >::_M_deallocate_node (this=<optimized out>, __p=<optimized out>)
    at /opt/gcc/8.1.0/include/c++/8.1.0/bits/stl_deque.h:610
#4  std::_Deque_base<AMQP::CopiedBuffer, std::allocator<AMQP::CopiedBuffer> >::_M_destroy_nodes (this=0x1be9700, __nfinish=0x1be9780, __nstart=<optimized out>)
    at /opt/gcc/8.1.0/include/c++/8.1.0/bits/stl_deque.h:744
#5  std::_Deque_base<AMQP::CopiedBuffer, std::allocator<AMQP::CopiedBuffer> >::~_Deque_base (this=0x1be9700, __in_chrg=<optimized out>)
    at /opt/gcc/8.1.0/include/c++/8.1.0/bits/stl_deque.h:666
#6  std::deque<AMQP::CopiedBuffer, std::allocator<AMQP::CopiedBuffer> >::~deque (this=0x1be9700, __in_chrg=<optimized out>) at /opt/gcc/8.1.0/include/c++/8.1.0/bits/stl_deque.h:1055
#7  std::queue<AMQP::CopiedBuffer, std::deque<AMQP::CopiedBuffer, std::allocator<AMQP::CopiedBuffer> > >::~queue (this=0x1be9700, __in_chrg=<optimized out>)
    at /opt/gcc/8.1.0/include/c++/8.1.0/bits/stl_queue.h:96
#8  AMQP::ConnectionImpl::~ConnectionImpl (this=0x1be9618, __in_chrg=<optimized out>) at /home/service/metricq-db-hta/lib/metricq/lib/amqpcpp/src/connectionimpl.cpp:44
#9  0x000000000048747a in AMQP::Connection::~Connection (this=0x1be9610, __in_chrg=<optimized out>)
    at /home/service/metricq-db-hta/lib/metricq/lib/asio/asio/include/asio/detail/impl/resolver_service_base.ipp:98
#10 AMQP::Connection::~Connection (this=0x1be9610, __in_chrg=<optimized out>) at /home/service/metricq-db-hta/lib/metricq/lib/amqpcpp/include/amqpcpp/connection.h:70
#11 std::default_delete<AMQP::Connection>::operator() (this=0x1bb5468, __ptr=0x1be9610) at /opt/gcc/8.1.0/include/c++/8.1.0/bits/unique_ptr.h:81
#12 std::unique_ptr<AMQP::Connection, std::default_delete<AMQP::Connection> >::~unique_ptr (this=0x1bb5468, __in_chrg=<optimized out>)
    at /opt/gcc/8.1.0/include/c++/8.1.0/bits/unique_ptr.h:274
#13 metricq::ConnectionHandler::~ConnectionHandler (this=0x1bb5440, __in_chrg=<optimized out>) at /home/service/metricq-db-hta/lib/metricq/src/connection_handler.hpp:76
#14 0x00000000004874d9 in metricq::ConnectionHandler::~ConnectionHandler (this=0x1bb5440, __in_chrg=<optimized out>)
    at /home/service/metricq-db-hta/lib/metricq/src/connection_handler.hpp:76
#15 0x000000000046c9a6 in std::default_delete<metricq::ConnectionHandler>::operator() (this=0x7ffca8605fe0, __ptr=<optimized out>)
    at /home/service/metricq-db-hta/lib/metricq/lib/amqpcpp/include/amqpcpp/channel.h:61
#16 std::unique_ptr<metricq::ConnectionHandler, std::default_delete<metricq::ConnectionHandler> >::~unique_ptr (this=0x7ffca8605fe0, __in_chrg=<optimized out>)
    at /opt/gcc/8.1.0/include/c++/8.1.0/bits/unique_ptr.h:274
#17 metricq::Connection::~Connection (this=0x7ffca8605f00, __in_chrg=<optimized out>) at /home/service/metricq-db-hta/lib/metricq/src/connection.cpp:64
#18 0x0000000000421234 in metricq::Db::~Db (this=0x7ffca8605f00, __in_chrg=<optimized out>)
    at /home/service/metricq-db-hta/lib/metricq/lib/asio/asio/include/asio/detail/scheduler_operation.hpp:44
#19 Db::~Db (this=0x7ffca8605f00, __in_chrg=<optimized out>) at /home/service/metricq-db-hta/src/db.hpp:59
#20 0x000000000040c5f8 in main (argc=5, argv=0x7ffca8606388) at /opt/gcc/8.1.0/include/c++/8.1.0/bits/unique_ptr.h:75
#21 0x00007fa85c3f42e1 in __libc_start_main (main=0x415910 <main>, argc=5, argv=0x7ffca8606388, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffca8606378) at ../csu/libc-start.c:291
#22 0x000000000041742a in _start () at /opt/gcc/8.1.0/include/c++/8.1.0/bits/char_traits.h:310
(gdb) 

```

**Comment by tilsche** [comment]
Please do the tests with 44b34d7, that should fix the two issues discussed today
 - not shutting down correctly after first close
 - duplicate close segfault
