### ISSUE TITLE
Exceptions in metricq-wizard-backend

### ISSUE THREAD

**Issue by zyzzyxdonta** [metricq/metricq#70]
Hi,

I tried setting up the development environment. Docker compose works, all containers are running. However there are multiple exceptions in the metricq-wizard-backend container.

```
wait-for-it.sh: waiting 15 seconds for couchdb-server:5984
wait-for-it.sh: couchdb-server:5984 is available after 1 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq-server:5672
wait-for-it.sh: rabbitmq-server:5672 is available after 10 seconds
[2021-03-05 13:14:57 +0000] [6] [INFO] Starting gunicorn 20.0.4
[2021-03-05 13:14:57 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2021-03-05 13:14:57 +0000] [6] [INFO] Using worker: aiohttp.GunicornWebWorker
[2021-03-05 13:14:57 +0000] [51] [INFO] Booting worker with pid: 51
Failed to find version of Configurator: module 'app.metricq.configurator' has no attribute '__version__'
[2021-03-05 13:14:59 +0000] [51] [ERROR] Exception in gunicorn worker
Traceback (most recent call last):
  File "/home/metricq/venv/lib/python3.9/site-packages/aiormq/channel.py", line 136, in rpc
    result = await asyncio.wait_for(
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 440, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/metricq/venv/lib/python3.9/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/metricq/venv/lib/python3.9/site-packages/aiohttp/worker.py", line 58, in run
    self.loop.run_until_complete(self._task)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/metricq/venv/lib/python3.9/site-packages/aiohttp/worker.py", line 83, in _run
    await runner.setup()
  File "/home/metricq/venv/lib/python3.9/site-packages/aiohttp/web_runner.py", line 232, in setup
    self._server = await self._make_server()
  File "/home/metricq/venv/lib/python3.9/site-packages/aiohttp/web_runner.py", line 331, in _make_server
    await self._app.startup()
  File "/home/metricq/venv/lib/python3.9/site-packages/aiohttp/web_app.py", line 389, in startup
    await self.on_startup.send(self)
  File "/home/metricq/venv/lib/python3.9/site-packages/aiohttp/signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/home/metricq/wizard/app/main.py", line 51, in startup
    await client.connect()
  File "/home/metricq/wizard/app/metricq/configurator.py", line 86, in connect
    await super().connect()
  File "/home/metricq/venv/lib/python3.9/site-packages/metricq/client.py", line 90, in connect
    await self._management_channel.declare_exchange(
  File "/home/metricq/venv/lib/python3.9/site-packages/aio_pika/robust_channel.py", line 125, in declare_exchange
    exchange = await super().declare_exchange(
  File "/home/metricq/venv/lib/python3.9/site-packages/aio_pika/channel.py", line 246, in declare_exchange
    await exchange.declare(timeout=timeout)
  File "/home/metricq/venv/lib/python3.9/site-packages/aio_pika/exchange.py", line 81, in declare
    return await asyncio.wait_for(
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 440, in wait_for
    return await fut
  File "/home/metricq/venv/lib/python3.9/site-packages/aiormq/channel.py", line 591, in exchange_declare
    return await self.rpc(
  File "/home/metricq/venv/lib/python3.9/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/metricq/venv/lib/python3.9/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 685, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/metricq/venv/lib/python3.9/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
aiormq.exceptions.ChannelNotFoundEntity: NOT_FOUND - no exchange 'metricq.broadcast' in vhost '/'
[2021-03-05 13:14:59 +0000] [51] [INFO] Worker exiting (pid: 51)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa9c4ea0370>
Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<Connection.__reader() running at /home/metricq/venv/lib/python3.9/site-packages/aiormq/base.py:168> wait_for=<Task pending name='Task-9' coro=<Connection.__reader() running at /home/metricq/venv/lib/python3.9/site-packages/aiormq/connection.py:373> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa9c4e430a0>()]> cb=[FutureStore.__on_task_done.<locals>.remover() at /home/metricq/venv/lib/python3.9/site-packages/aiormq/base.py:51, <TaskWakeupMethWrapper object at 0x7fa9c4e43910>()]> cb=[FutureStore.__on_task_done.<locals>.remover() at /home/metricq/venv/lib/python3.9/site-packages/aiormq/base.py:51]>
Task was destroyed but it is pending!
task: <Task pending name='Task-8' coro=<Connection.__heartbeat_task() running at /home/metricq/venv/lib/python3.9/site-packages/aiormq/connection.py:302> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa9c4e435b0>()]> cb=[FutureStore.__on_task_done.<locals>.remover() at /home/metricq/venv/lib/python3.9/site-packages/aiormq/base.py:51, Connection._on_heartbeat_done()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<Connection.__reader() running at /home/metricq/venv/lib/python3.9/site-packages/aiormq/connection.py:373> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa9c4e430a0>()]> cb=[FutureStore.__on_task_done.<locals>.remover() at /home/metricq/venv/lib/python3.9/site-packages/aiormq/base.py:51, <TaskWakeupMethWrapper object at 0x7fa9c4e43910>()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-14' coro=<ConnectionWatchdog.start.<locals>.watchdog() running at /home/metricq/venv/lib/python3.9/site-packages/metricq/connection_watchdog.py:77> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa9c4e43d90>()]>>
[2021-03-05 13:14:59 +0000] [53] [INFO] Booting worker with pid: 53
Failed to find version of Configurator: module 'app.metricq.configurator' has no attribute '__version__'
```

**Comment by bmario** [comment]
```aiormq.exceptions.ChannelNotFoundEntity: NOT_FOUND - no exchange 'metricq.broadcast' in vhost '/'```

That is a problem in order of sequence during the initial startup. We need to start A LOT of services, each their own dependencies to other services, but docker-compose doesn't manage dependencies between services as one would think. Thus during start-up, exceptions for missing dependencies are inevitable, especially during the first start. You can ignore those errors as long as, at some point, they disappear from the log, and everything works fine.

Try to reach the [wizard in a browser](http://localhost:3000/wizard/). If you get a webpage, it's fine.

**Comment by zyzzyxdonta** [comment]
Thanks for the quick reply. That's good to hear, I thought something went wrong because there weren't any other log messages indicating success after that.

I can access the wizard, but /wizard/source/source_list is stuck "Fetching Resources" and /wizard/client/client-list shows a network error. How would I go about finding the cause for this?

**Comment by bmario** [comment]
> I can access the wizard, but /wizard/source/source_list is stuck "Fetching Resources" and /wizard/client/client-list shows a network error. How would I go about finding the cause for this?

Oh no. That's a problem. But the initial error you posted should fix itself when you stop the docker-compose and start it again.

Which commit of the metricq repository are you using?

**Comment by zyzzyxdonta** [comment]
My colleague set the system up 2 days ago but I just ran `docker compose ... down; git pull; docker compose ... --build up -d`. Im on cbd7b2798df843e69cb76fc8a7a986e380c1fbc3. Also these changes were made:

```diff
diff --git a/docker-compose-development.yml b/docker-compose-development.yml
index 948941d..8f74169 100644
--- a/docker-compose-development.yml
+++ b/docker-compose-development.yml
@@ -46,7 +46,7 @@ services:
     depends_on:
       - metricq-wizard-backend
     ports:
-      - "127.0.0.1:3000:3000"
+      - "3000:3000"
     networks:
       - metricq-network
 
@@ -120,7 +120,7 @@ services:
       context: https://github.com/metricq/grafana-metricq-datasource.git
     image: metricq-grafana-server
     ports:
-      - "127.0.0.1:4000:3000"
+      - "4000:3000"
     depends_on:
       - metricq-grafana
     networks:
@@ -137,7 +137,7 @@ services:
     depends_on:
       - rabbitmq-server
     ports:
-      - "127.0.0.1:3002:4000"
+      - "3002:4000"
     restart: unless-stopped
     networks:
       - metricq-network
```

**Comment by kinnarr** [comment]
With `docker-compose down` all containers are removed. Running `docker-compose up` afterwards is like a first run.

If you are not connecting from localhost, you must also change the port binding for `metricq-wizard-backend` ([line 65](https://github.com/metricq/metricq/blob/master/docker-compose-development.yml#L65)) and the `API_URL` for `metricq-wizard-frontend` ([line 44](https://github.com/metricq/metricq/blob/master/docker-compose-development.yml#L44)).

**Comment by zyzzyxdonta** [comment]
Still the same problem

**Comment by kinnarr** [comment]
Can you check in the browser developer tools which backend URL is causing the network error?

**Comment by zyzzyxdonta** [comment]
localhost:8000/api/clients 😅 As api_url, I tried host.site.de, i.e. the same name as for connecting to the wizard from my browser at home. Is that correct?

**Comment by kinnarr** [comment]
After changing `API_URL` a rebuild is required

**Comment by zyzzyxdonta** [comment]
Awesome, it seems to work now. Thanks a bunch!
